"""
Checkout Recovery Intelligence Dashboard.

User-facing visibility layer for the checkout recovery agent.

Pipeline:
    Detect -> Diagnose -> Decide -> Recover -> Measure
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st


# ================================================================
# PROJECT PATHS
# ================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_PATH = PROJECT_ROOT / "data" / "sessions.json"

AUDIT_DIR = PROJECT_ROOT / "audit"
DASHBOARD_AUDIT_PATH = AUDIT_DIR / "dashboard_run.jsonl"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


from src.recovery_agent import process_sessions
from src.revenue_simulator import (
    simulate_results,
    summarize_revenue,
)


# ================================================================
# PAGE CONFIG
# ================================================================

st.set_page_config(
    page_title="Checkout Recovery Intelligence",
    page_icon="💳",
    layout="wide",
    initial_sidebar_state="collapsed",
)


# ================================================================
# DATA LOADING
# ================================================================

@st.cache_data
def load_sessions() -> list[dict]:
    """Load the generated checkout dataset."""

    with DATA_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def run_pipeline(
    sessions: list[dict],
):
    """
    Run the existing recovery pipeline.

    The dashboard does not make its own decisions.
    It calls the actual recovery agent.
    """

    AUDIT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Start every dashboard run with a clean audit file.
    if DASHBOARD_AUDIT_PATH.exists():
        DASHBOARD_AUDIT_PATH.unlink()

    results = process_sessions(
        sessions,
        audit_path=DASHBOARD_AUDIT_PATH,
    )

    simulations = simulate_results(
        sessions,
        results,
    )

    summary = summarize_revenue(
        simulations,
    )

    return results, simulations, summary


def load_dashboard_audit() -> list[dict]:
    """Load audit records generated by the current dashboard run."""

    if not DASHBOARD_AUDIT_PATH.exists():
        return []

    records = []

    with DASHBOARD_AUDIT_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:

        for line in file:
            line = line.strip()

            if line:
                records.append(
                    json.loads(line)
                )

    return records


# ================================================================
# LOAD PIPELINE
# ================================================================

try:
    sessions = load_sessions()

except FileNotFoundError:
    st.error(
        "Dataset not found. Run the data generator first."
    )
    st.stop()


results, simulations, summary = run_pipeline(
    sessions
)


# ================================================================
# BUILD DATAFRAME
# ================================================================

rows = []

for session, result, simulation in zip(
    sessions,
    results,
    simulations,
):

    diagnosis = result.get("diagnosis")
    policy = result.get("policy")
    execution = result.get("execution")

    rows.append(
        {
            "session_id": session["session_id"],
            "status": session.get("status"),
            "cart_value": session.get(
                "cart_value",
                0.0,
            ),
            "payment_method": session.get(
                "payment_method"
            ),
            "device": session.get(
                "device"
            ),
            "cause": (
                diagnosis.get("cause")
                if diagnosis
                else None
            ),
            "confidence": (
                diagnosis.get("confidence")
                if diagnosis
                else None
            ),
            "decision": (
                policy.get("decision")
                if policy
                else None
            ),
            "action": (
                policy.get("action")
                if policy
                else None
            ),
            "execution_status": (
                execution.get(
                    "execution_status"
                )
                if execution
                else None
            ),
            "eligible": simulation.get(
                "eligible",
                False,
            ),
            "recovered": simulation.get(
                "recovered",
                False,
            ),
            "recovered_revenue": simulation.get(
                "recovered_revenue",
                0.0,
            ),
        }
    )


df = pd.DataFrame(rows)

abandoned_df = df[
    df["status"] == "abandoned"
].copy()


# ================================================================
# HEADER
# ================================================================

st.title(
    "Checkout Recovery Intelligence"
)

st.caption(
    "An agentic revenue recovery system that detects checkout "
    "drop-off, diagnoses likely causes, applies bounded recovery "
    "policies, and measures simulated revenue impact."
)

st.markdown(
    """
**DETECT** → **DIAGNOSE** → **DECIDE** → **RECOVER** → **MEASURE**
"""
)

st.divider()


# ================================================================
# PRIMARY BUSINESS METRICS
# ================================================================

st.subheader("Business Impact")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Checkout Sessions",
        f"{summary['total_sessions']:,}",
    )

with col2:
    st.metric(
        "Abandoned Checkouts",
        f"{len(abandoned_df):,}",
    )

with col3:
    st.metric(
        "Value at Risk",
        f"₹{summary['value_at_risk']:,.2f}",
    )

with col4:
    st.metric(
        "Recovered Revenue",
        f"₹{summary['recovered_revenue']:,.2f}",
    )


col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Eligible Sessions",
        f"{summary['eligible_sessions']:,}",
    )

with col2:
    st.metric(
        "Eligible Value",
        f"₹{summary['eligible_value']:,.2f}",
    )

with col3:
    st.metric(
        "Successful Recoveries",
        f"{summary['successful_recoveries']:,}",
    )

with col4:
    st.metric(
        "Revenue Recovery Rate",
        f"{summary['revenue_recovery_rate'] * 100:.2f}%",
    )


st.divider()


# ================================================================
# DIAGNOSIS + DECISION
# ================================================================

st.subheader("Agent Intelligence")

col1, col2 = st.columns(2)

with col1:

    st.markdown("#### Why are customers dropping off?")

    cause_counts = (
        abandoned_df["cause"]
        .fillna("unknown")
        .value_counts()
        .sort_values()
    )

    st.bar_chart(
        cause_counts,
        horizontal=True,
    )


with col2:

    st.markdown("#### What did the agent decide?")

    decision_counts = (
        abandoned_df["decision"]
        .fillna("no_action")
        .value_counts()
        .sort_values()
    )

    st.bar_chart(
        decision_counts,
        horizontal=True,
    )


st.divider()


# ================================================================
# CHECKOUT BEHAVIOR
# ================================================================

st.subheader("Checkout Behavior")

col1, col2 = st.columns(2)

with col1:

    st.markdown(
        "#### Abandonments by payment method"
    )

    payment_counts = (
        abandoned_df["payment_method"]
        .value_counts()
        .sort_values()
    )

    st.bar_chart(
        payment_counts,
        horizontal=True,
    )


with col2:

    st.markdown(
        "#### Abandonments by device"
    )

    device_counts = (
        abandoned_df["device"]
        .value_counts()
        .sort_values()
    )

    st.bar_chart(
        device_counts,
        horizontal=True,
    )


st.divider()


# ================================================================
# RECOVERY PERFORMANCE
# ================================================================

st.subheader(
    "Recovery Performance by Cause"
)

recovery_df = df[
    df["eligible"] == True
].copy()


if not recovery_df.empty:

    recovery_by_cause = (
        recovery_df
        .groupby("cause")
        .agg(
            eligible_sessions=(
                "session_id",
                "count",
            ),
            recovered_sessions=(
                "recovered",
                "sum",
            ),
            eligible_value=(
                "cart_value",
                "sum",
            ),
            recovered_revenue=(
                "recovered_revenue",
                "sum",
            ),
        )
        .sort_index()
    )

    recovery_by_cause[
        "recovery_rate"
    ] = (
        recovery_by_cause[
            "recovered_sessions"
        ]
        / recovery_by_cause[
            "eligible_sessions"
        ]
    )

    recovery_by_cause[
        "revenue_recovery_rate"
    ] = (
        recovery_by_cause[
            "recovered_revenue"
        ]
        / recovery_by_cause[
            "eligible_value"
        ]
    )

    display_df = recovery_by_cause.copy()

    display_df[
        "recovery_rate"
    ] *= 100

    display_df[
        "revenue_recovery_rate"
    ] *= 100

    st.dataframe(
        display_df.style.format(
            {
                "eligible_sessions": "{:,}",
                "recovered_sessions": "{:,}",
                "eligible_value": "₹{:,.2f}",
                "recovered_revenue": "₹{:,.2f}",
                "recovery_rate": "{:.2f}%",
                "revenue_recovery_rate": "{:.2f}%",
            }
        ),
        use_container_width=True,
    )

else:

    st.info(
        "No recovery-eligible sessions found."
    )


st.divider()


# ================================================================
# SESSION EXPLORER
# ================================================================

st.subheader("Session Explorer")

filter1, filter2, filter3 = st.columns(3)

with filter1:

    selected_status = st.selectbox(
        "Status",
        [
            "All",
            "abandoned",
            "completed",
        ],
    )


with filter2:

    selected_decision = st.selectbox(
        "Decision",
        [
            "All",
            "recover",
            "no_action",
            "escalate",
        ],
    )


with filter3:

    causes = sorted(
        str(value)
        for value in df["cause"]
        .dropna()
        .unique()
    )

    selected_cause = st.selectbox(
        "Diagnosis",
        ["All"] + causes,
    )


filtered_df = df.copy()


if selected_status != "All":

    filtered_df = filtered_df[
        filtered_df["status"]
        == selected_status
    ]


if selected_decision != "All":

    filtered_df = filtered_df[
        filtered_df["decision"]
        == selected_decision
    ]


if selected_cause != "All":

    filtered_df = filtered_df[
        filtered_df["cause"]
        == selected_cause
    ]


display_columns = [
    "session_id",
    "status",
    "cart_value",
    "payment_method",
    "device",
    "cause",
    "confidence",
    "decision",
    "action",
    "eligible",
    "recovered",
    "recovered_revenue",
]


st.dataframe(
    filtered_df[
        display_columns
    ],
    use_container_width=True,
    height=400,
)


st.caption(
    f"Showing {len(filtered_df):,} matching sessions."
)


st.divider()


# ================================================================
# AUDIT TRAIL
# ================================================================

st.subheader(
    "Decision Audit Trail"
)

audit_records = load_dashboard_audit()


if audit_records:

    audit_df = pd.DataFrame(
        audit_records
    )

    st.dataframe(
        audit_df.tail(100),
        use_container_width=True,
        height=400,
    )

    st.caption(
        f"Current run contains {len(audit_df):,} "
        "audited decisions. Showing the latest 100."
    )

else:

    st.info(
        "No audit records generated yet."
    )


# ================================================================
# FOOTER
# ================================================================

st.divider()

st.caption(
    "Checkout Recovery Intelligence • "
    "Simulation environment • "
    "Recovery actions are simulated and do not trigger real payments."
)